### ISSUE TITLE
alexa rank not working correctly for subdomains

### ISSUE THREAD

**Issue by gsar** [blatyo/page_rankr#41]
Looks like this affects stuff like wordpress domains.  For example:

  $ PageRankr.rank('cbmilstein.wordpress.com', :alexa_global)
  => {:alexa_global=>31}

  $ curl -s 'http://data.alexa.com/data?cli=10&dat=snbamz&url=cbmilstein.wordpress.com' | grep -i popularity
  <POPULARITY URL="cbmilstein.wordpress.com/" TEXT="3847224" SOURCE="panel"/>

  $ curl -s 'http://data.alexa.com/data?cli=10&dat=snbamz&url=wordpress.com' | grep -i popularity
  <POPULARITY URL="wordpress.com/" TEXT="31" SOURCE="panel"/>

So the rank returned should be 3847224, not 31.

Any reason the default for supported_components is :domain and not :subdomain for alexa?

**Comment by blatyo** [comment]
I honestly don't recall. I'd happily accept a pull request that changes it as long as it works. Also, add this example to the edge_cases_spec. Do something reasonable, that won't break if the rank changes. For example `it{ subject[:alexa_global].should be > 60 }`.

Thanks for reporting the issue

**Comment by blatyo** [comment]
This was

**Comment by blatyo** [comment]
Use 4.6.0, which fixes this
