### ISSUE TITLE
Sometimes Callback Doesnt Come Back

### ISSUE THREAD

**Issue by AbdullahMuhammad** [blatyo/page_rankr#45]
Hi I am using your gem in a project of a client. Its on production for a while now.
Some times my callbacks doesnt come back and my system keeps on waiting.
What i have found so far is that this service limits calls from a same machine.
"One of the annoying things about each of these services is that they really don't like you scraping data from them. In order to deal with this issue, they throttle traffic from a single machine. The simplest way to get around this is to use proxy machines to make the requests"
How can i debug a call that is not returning.
Any ideas are appreciated.

**Comment by blatyo** [comment]
If the issue is happening, you can run a specific tracker:

``` ruby
require 'page_rankr/ranks/google'

tracker = PageRankr::Ranks::Google.new("myawesomesite.com")
tracker.run
```

`tracker` has the intermediary values that get processed from the web request.

https://github.com/blatyo/page_rankr/blob/master/lib/page_rankr/tracker.rb#L44-L46

**Comment by AbdullahMuhammad** [comment]
tracker.run is returning me nil

**Comment by AbdullahMuhammad** [comment]
Sometimes i am getting a nil and sometimes i get an integer. This is returning me page rank. How can it help me. Sorry if i am missing anything.

**Comment by AbdullahMuhammad** [comment]
i am running following in my console
PageRankr.ranks("http://www.espncricinfo.com", :google)
and its response is not coming back. Does PageRankr works for dynamic ips ?

**Comment by blatyo** [comment]
Look at `tracker.body` after you have done `tracker.run`. That is the raw body returned from the request. That should be sufficient for you to see what the issue is.

**Comment by AbdullahMuhammad** [comment]
Yes i did that. But from my local machine i dont get the call back. I am testing all this from a staging machine with static ip. Any ideas sir.
