### ISSUE TITLE
Insane public_suffix version requirement

### ISSUE THREAD

**Issue by mrbrdo** [blatyo/page_rankr#48]
Why not relax the version requirement a little bit? All you're using is `PublicSuffix.parse` which is the most core possible thing in the library. I don't see any way the author would change the API of this method without bumping the major version (to be honest I don't even see him changing it at all, ever). And this method has existed in public_suffix since forever. So why not make it "< 2.0"?

**Comment by blatyo** [comment]
I'll accept a pull request that changes it to `'~> 1.0'`

**Comment by mrbrdo** [comment]
lol fine https://github.com/blatyo/page_rankr/pull/49

**Comment by blatyo** [comment]
Version 4.6.1 has your change. By the way, the reason I said '~> 1.0' is because `PublicSuffix` < 1.0.0 was called `PublicSuffixService`, which would break this gem.

**Comment by mrbrdo** [comment]
:+1:
