### ISSUE TITLE
"A JSON text must at least contain two octets!"

### ISSUE THREAD

**Issue by mikeover** [blatyo/page_rankr#50]
Getting that error in the parse line in:

 # * *array_class*: Defaults to Array
  def parse(source, opts = {})
    Parser.new(source, opts).parse
  end

Full trace:

json (1.8.3) lib/json/common.rb:155:in `initialize'
json (1.8.3) lib/json/common.rb:155:in `new'
json (1.8.3) lib/json/common.rb:155:in `parse'
PageRankr (4.4.1) lib/page_rankr/tracker.rb:56:in `content'
PageRankr (4.4.1) lib/page_rankr/tracker.rb:45:in `block in run'
PageRankr (4.4.1) lib/page_rankr/request.rb:15:in `perform'
PageRankr (4.4.1) lib/page_rankr/tracker.rb:43:in `run'
PageRankr (4.4.1) lib/page_rankr/trackers.rb:36:in `block in build_thread'

**Comment by mikeover** [comment]
Same thing happens in 4.6.1, it's when fetching socials

**Comment by blatyo** [comment]
Can you provide a failing test case? When I run the tests, this works fine.

A couple things would be useful. 

1. Which social has an issue?
2. Which url are you checking?
3. Which version of ruby are you using?

Thanks

**Comment by mikeover** [comment]
I found the problem goes away when I don't fetch the vk socials.

**Comment by kennyfrc** [comment]
Hi blatyo,

I'm also experiencing the same issues. The social that has a problem is Twitter. I'm using `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]`.

What failed:
```
PageRankr.socials('http://www.google.com/', :twitter)

JSON::ParserError: A JSON text must at least contain two octets!
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:56:in `content'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:45:in `block in run'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/request.rb:15:in `perform'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:43:in `run'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/trackers.rb:36:in `block in build_thread'
```
Another case:
```
PageRankr.socials('http://www.stevefaeembra.com/blog/2016/1/10/toponymy-mapping-place-name-patterns-in-great-britain-with-qgis', :twitter)

JSON::ParserError: A JSON text must at least contain two octets!
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:56:in `content'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:45:in `block in run'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/request.rb:15:in `perform'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/tracker.rb:43:in `run'
	from /Users/kennyfrc/.rvm/gems/ruby-2.2.1/gems/PageRankr-4.6.1/lib/page_rankr/trackers.rb:36:in `block in build_thread'
```

**Comment by kennyfrc** [comment]
Likely helpful: https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

**Comment by blatyo** [comment]
Thanks @kennyfrc. That error implies that the response coming back from twitter is not valid JSON. The link you point to implies that they have or will be removing the api used. If that's the case, I'd accept a PR to remove that endpoint.

**Comment by kennyfrc** [comment]
cool -- will look into it @blatyo
