### ISSUE TITLE
Facebook, Twitter, and StumbleUpon social links all returning 0

### ISSUE THREAD

**Issue by mikeover** [blatyo/page_rankr#51]
Even when looking up google.com, it's returning 0 social signals for facebook, twitter, and stumbleupon. Google Plus is often times returning 0 as well. Linked In and Pinterest seem to always return valid results but the other ones are spotty.

**Comment by blatyo** [comment]
You are likely being throttled. The solution for that is to make your requests through a pool of proxies.

This library does not have the ability to detect throttling. Though, if someone wanted to build that, I'd happily merge it.
