### ISSUE TITLE
Remove Google Page Rank

### ISSUE THREAD

**Issue by harlow** [blatyo/page_rankr#52]
We've been seeing empty results for all calls to Page Rank for some time now. Looks like its been deprecated:

http://searchengineland.com/google-has-confirmed-they-are-removing-toolbar-pagerank-244230
http://mysiteauditor.com/blog/is-google-pagerank-dead/

**Comment by blatyo** [comment]
Thanks, but see the comment here: https://github.com/blatyo/page_rankr/pull/53#issuecomment-226655404
